### ISSUE TITLE
i2c clock allocator flag

### ISSUE THREAD

**Issue by richardhenryhopper** [danak6jq/ESP32-WSPR#2]
Error building in ESP-IDF 4.4, as the i2c clock allocator flag needs to be set in i2c_master_init(). 
conf.clk_flags = 0;

**Comment by danak6jq** [comment]
Is there a PR for this? Would love to review and merge

**Comment by richardhenryhopper** [comment]
I don't think so, Richard

**Comment by danak6jq** [comment]
I apologize for the year-long delay - just realized you had a PR! Merged. Thank you!

**Comment by richardhenryhopper** [comment]
Welcome Dana :)

I just tested it with my ESP32 and spotted this missing flag issue.
I am now working on some more transmitter hardware but intend to use the
firmware in the future.

Best wishes,
Richard Hopper
Cambridge, UK
